#
# Copyright (C) 2021 The Android Open Source Project
# Copyright (C) 2021 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/infinix/Nova

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic

# Assert
TARGET_OTA_ASSERT_DEVICE := Nova

# Bootloader"
TARGET_BOOTLOADER_BOARD_NAME := CY-X627-H624

# Partition Size
BOARD_HAS_LARGE_FILESYSTEM := true 
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 36864000 #33554432 #This is the maximum known partition size, but it can be higher, so we just omit it
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2826960896
BOARD_METADATAIMAGE_PARTITION_SIZE := 33554432
BOARD_VENDORIMAGE_PARTITION_SIZE := 436207616
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true

# Partition Type
BOARD_RECOVERYIMAGE_PARTITION_TYPE := ext4
BOARD_BOOTIMAGE_PARTITION_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_TYPE := ext4
BOARD_METADATAIMAGE_PARTITION_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATA_PARTITION_TYPE := f2fs
BOARD_USERDATAIMAGE_PARTITION_TYPE := f2fs

# File Systems
BOARD_RECOVERYMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_BOOTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_METADATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USERDATA_FILE_SYSTEM_TYPE := f2fs

# Target
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_COPY_OUT_VENDOR := vendor
RECOVERY_SDCARD_ON_DATA := true

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1 cgroup_no_v1=memory,io buildvariant=user
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/zImage-dtb
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x11b00000
BOARD_KERNEL_TAGS_OFFSET := 0x07880000
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_IMAGE_NAME := zImage-dtb
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
TARGET_KERNEL_SOURCE := kernel/infinix/Nova
TARGET_KERNEL_CONFIG := Nova_defconfig

# Platform
TARGET_BOARD_PLATFORM := mt6761
BOARD_USES_METADATA_PARTITION := true
BOARD_SUPPRESS_SECURE_ERASE := true
TARGET_USES_MKE2FS := true

# Debugging
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

ifeq ($(TARGET_USES_LOGD), true)
    RELINK_SOURCE_FILES += $(TARGET_OUT_EXECUTABLES)/logd
    RELINK_SOURCE_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libsysutils.so
    RELINK_SOURCE_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libnl.so
endif
ifeq ($(TWRP_INCLUDE_LOGCAT), true)
    RELINK_SOURCE_FILES += $(TARGET_OUT_EXECUTABLES)/logcat
endif

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

#### OFX Configs ####
#FOX_DRASTIC_SIZE_REDUCTION := 1
#FOX_EXTREME_SIZE_REDUCTION := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_ZIP_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_USE_NANO_EDITOR := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_USE_NEW_MAGISKBOOT := 1
OF_FORCE_DISABLE_DM_VERITY_FORCED_ENCRYPTION := 1
OF_DISABLE_DM_VERITY_FORCED_ENCRYPTION := 1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
OF_FLASHLIGHT_ENABLE := 0
OF_MAINTAINER := A-Rehman
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_STATUS_H := 80
OF_SKIP_MULTIUSER_FOLDERS_BACKUP := 1

# OFX_R INFO
FOX_VARIANT := Infinix_X627
FOX_VERSION := 3.1
FOX_BUILD_TYPE := Final
OF_MAINTAINER := A-Rehman

# OFX_R Partition
FOX_RECOVERY_INSTALL_PARTITION := /dev/block/platform/bootdevice/by-name/recovery
FOX_RECOVERY_SYSTEM_PARTITION := /dev/block/platform/bootdevice/by-name/system
FOX_RECOVERY_BOOT_PARTITION := /dev/block/platform/bootdevice/by-name/boot
FOX_RECOVERY_VENDOR_PARTITION := /dev/block/platform/bootdevice/by-name/vendor
FOX_RECOVERY_METADATA_PARTITION := /dev/block/platform/bootdevice/by-name/metadata
FOX_RECOVERY_USERDATA_PARTITION := /dev/block/platform/bootdevice/by-name/userdata

# TWRP Configuration

TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1520
#TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
